#!/usr/bin/env python3
"""
Generate `web/react/icons.jsx` from the `lucide-static` package.

The published page has a CDN allowlist, and an icon font or stylesheet from the
wrong host fails silently - so the artwork is compiled in rather than fetched.
Add a name to WANT and re-run `npm run build:icons`.
"""

import pathlib
import re

SRC = pathlib.Path('node_modules/lucide-static/icons')
OUT = pathlib.Path('web/react/icons.jsx')

WANT = """mountain swords zap shield cat sparkles hand-coins umbrella wind flame scale
cloud-lightning waves sprout heart crosshair activity feather sunrise hourglass
chevron-right rotate-ccw gauge target circle-dot shield-plus hammer droplets
snowflake skull sun moon eye swatch-book""".split()

HEADER = """/**
 * Lucide icons, compiled in rather than fetched.
 *
 * Generated by `npm run build:icons` from the `lucide-static` package, so the
 * artwork is genuinely Lucide (ISC licensed) with no runtime dependency - the
 * published page has a CDN allowlist, and a stylesheet or icon font from the
 * wrong host fails silently.
 *
 * Do not edit by hand. Add a name to WANT in scripts/build-icons.py instead.
 */

const Glyph = ({ size = 20, className = '', strokeWidth = 2, ...rest }) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth={strokeWidth}
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    aria-hidden="true"
    {...rest}
  />
);

"""


def pascal(name: str) -> str:
    return ''.join(part.capitalize() for part in name.split('-'))


def camel(attr: str) -> str:
    head, *rest = attr.split('-')
    return head + ''.join(part.capitalize() for part in rest)


def main() -> None:
    parts, missing = [], []
    for name in WANT:
        path = SRC / f'{name}.svg'
        if not path.exists():
            missing.append(name)
            continue
        text = path.read_text()
        inner = text[text.index('>', text.index('<svg')) + 1:text.rindex('</svg>')].strip()
        # JSX needs camelCased hyphenated attributes.
        inner = re.sub(r'\b([a-z]+(?:-[a-z]+)+)=', lambda m: camel(m.group(1)) + '=', inner)
        inner = re.sub(r'\n\s+', '\n      ', inner)
        parts.append(f'export const {pascal(name)} = (p) => (\n  <Glyph {{...p}}>\n      {inner}\n  </Glyph>\n);')

    OUT.write_text(HEADER + '\n\n'.join(parts) + '\n')
    print(f'{len(parts)} icons written to {OUT}' + (f'; missing: {missing}' if missing else ''))


if __name__ == '__main__':
    main()
