// Pulls the handful of game-icons.net glyphs the UI uses out of the full
// iconify set and writes them to src/ui/icons/gameIcons.ts, so the app bundle
// carries ~50 icons instead of 4,000.
//
// Icons by Lorc, Delapouite and contributors, https://game-icons.net, CC BY 3.0.
import { readFileSync, writeFileSync } from 'node:fs';

const set = JSON.parse(
  readFileSync(new URL('../node_modules/@iconify-json/game-icons/icons.json', import.meta.url), 'utf8'),
);

const NAMES = [
  // abilities
  'sparkling-sabre', 'templar-shield', 'holy-symbol', 'mailed-fist', 'arrows-shield', 'heart-shield',
  'war-axe', 'hammer-drop', 'axe-swing', 'energy-arrow', 'striking-arrows', 'moon',
  'crossed-swords', 'two-shadows', 'sword-spin', 'crossed-axes', 'rally-the-troops', 'wolf-howl',
  'sun-radiations', 'healing', 'sunrise', 'magic-swirl', 'star-swirl', 'missile-swarm',
  // equipment
  'warhammer', 'spell-book', 'book-cover', 'gauntlet', 'ring', 'magic-shield', 'battle-axe', 'belt',
  'gem-pendant', 'feather-necklace', 'pocket-bow', 'engagement-ring', 'black-belt', 'ancient-sword',
  'flaming-claw', 'wolf-head', 'horned-helm', 'armor-vest', 'crystal-wand', 'crystal-growth', 'robe',
  'powder-bag', 'wizard-staff', 'orb-wand',
  // interface
  'feathered-wing', 'hourglass', 'skull-crack', 'snail', 'eye-shield', 'crystal-ball', 'shield',
  'broadsword', 'drop', 'swords-emblem', 'sound-on', 'sound-off', 'scroll-unfurled', 'crowned-skull',
  'laurel-crown', 'broken-shield', 'upgrade', 'speedometer', 'dice-six-faces-five',
];

const out = {};
for (const n of NAMES) {
  const icon = set.icons[n];
  if (!icon) throw new Error(`missing icon: ${n}`);
  // iconify bodies are <path> markup on a 512x512 grid; keep only the d= data
  const paths = [...icon.body.matchAll(/ d="([^"]+)"/g)].map((m) => m[1]);
  out[n] = paths.join(' ');
}

writeFileSync(
  new URL('../src/ui/icons/gameIcons.ts', import.meta.url),
  `// Generated by scripts/extract-icons.mjs. Do not edit.
// Icons by Lorc, Delapouite and contributors, https://game-icons.net, CC BY 3.0.
// Each value is SVG path data on a 512x512 viewBox.
export const GAME_ICONS = ${JSON.stringify(out, null, 1)} as const;

export type GameIconName = keyof typeof GAME_ICONS;
`,
);
console.log(`wrote ${NAMES.length} icons`);
